### ISSUE TITLE
Problem with new apktool and objection tools

### ISSUE THREAD

**Issue by yodiaditya** [NickstaDB/patch-apk#12]
I got this issue
```
Traceback (most recent call last):
  File "C:\Python36\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "patch-apk.py", line 620, in <module>
    main()
  File "patch-apk.py", line 44, in main
    shutil.move(apkfile[:-4] + ".objection.apk", apkfile)
  File "C:\Python36\lib\shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "C:\Python36\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python36\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 
```

When I executed the objection its perfectly fine until i saw this line :

`ret = subprocess.run(["objection", "patchapk", "--skip-resources", "-s", apkfile], stdout=getStdout())`

To make it works, I need to change the code to:

`ret = subprocess.run(["objection", "patchapk", "--skip-resources", "--ignore-nativelibs", "-s", apkfile], stdout=getStdout())`

**Comment by NickstaDB** [comment]
Thanks, this should now be resolved.
