### ISSUE TITLE
FileNotFoundError because of apktool

### ISSUE THREAD

**Issue by rkba** [NickstaDB/patch-apk#15]
For some strange reason

```sh
$ python3 ./patch-apk/patch-apk.py "org.lineageos.lockclock"
Getting APK path(s) for package: org.lineageos.lockclock
[+] APK path: /system/app/LockClock/LockClock.apk

Pulling APK file(s) from device.
[+] Pulling: org.lineageos.lockclock-LockClock.apk

Patching org.lineageos.lockclock-LockClock.apk with objection.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3tw5u79r/org.lineageos.lockclock-LockClock.objection.apk' -> '/tmp/tmp3tw5u79r/org.lineageos.lockclock-LockClock.apk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./patch-apk/patch-apk.py", line 632, in <module>
    main()
  File "./patch-apk/patch-apk.py", line 49, in main
    shutil.move(apkfile[:-4] + ".objection.apk", apkfile)
  File "/usr/local/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3tw5u79r/org.lineageos.lockclock-LockClock.objection.apk'
```

----

Ah, when rerunning I got the reasoin:
```
python3 ./patch-apk/patch-apk.py --debug-output "org.lineageos.lockclock"
Getting APK path(s) for package: org.lineageos.lockclock
[+] APK path: /system/app/LockClock/LockClock.apk

Pulling APK file(s) from device.
[+] Pulling: org.lineageos.lockclock-LockClock.apk
/system/app/LockClock/LockClock.apk: 1 file pulled. 21.4 MB/s (4567351 bytes in 0.203s)

Patching org.lineageos.lockclock-LockClock.apk with objection.
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using latest Github gadget version: 12.11.7
Patcher will be using Gadget version: 12.11.7
Detected apktool version as: 2.3.4-dirty
apktool version should be at least 2.4.1
Please see the following URL for more information: https://github.com/sensepost/objection/wiki/Apktool-Upgrades
apktool is not ready for use
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpuak1e5jj.apktemp.objection.apk'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpx7w85ftu/org.lineageos.lockclock-LockClock.objection.apk' -> '/tmp/tmpx7w85ftu/org.lineageos.lockclock-LockClock.apk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./patch-apk/patch-apk.py", line 632, in <module>
    main()
  File "./patch-apk/patch-apk.py", line 49, in main
    shutil.move(apkfile[:-4] + ".objection.apk", apkfile)
  File "/usr/local/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpx7w85ftu/org.lineageos.lockclock-LockClock.objection.apk'
```

Maybe you should provide this more upfront or check for that version earlier.

**Comment by NickstaDB** [comment]
Set up your environment properly.

**Comment by rkba** [comment]
Sure, this was about the suggestion that this tool could offer a more useful error in case such an error happens:
> Maybe you should provide this more upfront or check for that version earlier.
