### ISSUE TITLE
Errors while patching APK and AndroidManifest parse error

### ISSUE THREAD

**Issue by rkba** [NickstaDB/patch-apk#16]
Also note the app does not correctly start anymore: https://github.com/sensepost/objection/issues/397

```
$ python3 ./patch-apk/patch-apk.py --debug-output ******
Getting APK path(s) for package: ******
[+] APK path: /data/app/******-IOTGWLxz5wTYpg1WVYBqlQ==/base.apk

Pulling APK file(s) from device.
[+] Pulling: ******-base.apk
/data/app/******-IOTGWLxz5wTYpg1W...ile pulled. 18.9 MB/s (25191849 bytes in 1.269s)

Patching ******-base.apk with objection.
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using latest Github gadget version: 12.11.7
Patcher will be using Gadget version: 12.11.7
Detected apktool version as: 2.4.1
Running apktool empty-framework-dir...
Unpacking /tmp/tmp5m9mv6ht/******-base.apk
An error may have occurred while extracting the APK.
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: Couldn't create directory /tmp/tmpaq2qudc6.apktemp/smali_classes3/com/google/zxing/pdf417
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:101)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:39)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:96)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:164)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: Couldn't create directory /tmp/tmpaq2qudc6.apktemp/smali_classes3/com/google/zxing/pdf417
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
	... 7 more
Caused by: org.jf.util.ExceptionWithContext: Couldn't create directory /tmp/tmpaq2qudc6.apktemp/smali_classes3/com/google/zxing/pdf417
	at org.jf.util.ClassFileNameHandler$DirectoryEntry.isCaseSensitive(ClassFileNameHandler.java:357)
	at org.jf.util.ClassFileNameHandler$FileSystemEntry.getNormalizedName(ClassFileNameHandler.java:254)
	at org.jf.util.ClassFileNameHandler$DirectoryEntry.addChild(ClassFileNameHandler.java:308)
	at org.jf.util.ClassFileNameHandler.addUniqueChild(ClassFileNameHandler.java:135)
	at org.jf.util.ClassFileNameHandler.addUniqueChild(ClassFileNameHandler.java:146)
	at org.jf.util.ClassFileNameHandler.addUniqueChild(ClassFileNameHandler.java:146)
	at org.jf.util.ClassFileNameHandler.addUniqueChild(ClassFileNameHandler.java:146)
	at org.jf.util.ClassFileNameHandler.addUniqueChild(ClassFileNameHandler.java:146)
	at org.jf.util.ClassFileNameHandler.getUniqueFilenameForClass(ClassFileNameHandler.java:127)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:121)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

App already has android.permission.INTERNET
Target class not specified, searching for launchable activity instead...
Unable to determine the launchable activity using aapt, trying to manually parse the AndroidManifest for activity aliases...
Cannot manually parse the AndroidManifest.xml when --skip-resources is set, remove this and try again.
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/objection/console/cli.py", line 371, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 200, in patch_android_apk
    patcher.inject_load_library(target_class=target_class)
  File "/usr/local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 782, in inject_load_library
    target_class if target_class else self._get_launchable_activity())
  File "/usr/local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 341, in _get_launchable_activity
    manifest = self._get_android_manifest()
  File "/usr/local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 287, in _get_android_manifest
    raise Exception('Cannot --skip-resources when trying to manually parse the AndroidManifest.xml')
Exception: Cannot --skip-resources when trying to manually parse the AndroidManifest.xml
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpaq2qudc6.apktemp.objection.apk'
Error: Failed to run 'objection patchapk --skip-resources -s /tmp/tmp5m9mv6ht/******-base.apk'.
Run with --debug-output for more information.
```

Debian 10

```
+ adb --version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5
Installed as /usr/lib/android-sdk/platform-tools/adb
+ frida --version
12.11.7
+ objection version
objection: 1.9.5
+ python3 --version
Python 3.7.8
+ apktool -version
2.4.1
```

**Comment by NickstaDB** [comment]
This is a single APK application according to your output. Try manually decompiling and rebuilding the APK with apktool. If that doesn't work then there may be anti-reversing measures in place intended to prevent tampering with the APK. Either way, this is beyond the scope of what `patch-apk` does.
