### ISSUE TITLE
FileNotFoundError when rebuilding as a single APK

### ISSUE THREAD

**Issue by andrizmitnick** [NickstaDB/patch-apk#18]
```Extracting individual APKs with apktool.
[+] Extracting: F:\CACHE~1\tmp57ha9e4h\com.-base.apk
Traceback (most recent call last):
  File "D:\.user\_app\patch-apk\patch-apk.py", line 632, in <module>
    main()
  File "D:\.user\_app\patch-apk\patch-apk.py", line 30, in main
    apkfile = getTargetAPK(pkgname, apkpaths, tmppath, args.disable_styles_hack)
  File "D:\.user\_app\patch-apk\patch-apk.py", line 250, in getTargetAPK
    return combineSplitAPKs(pkgname, localapks, tmppath, disableStylesHack)
  File "D:\.user\_app\patch-apk\patch-apk.py", line 267, in combineSplitAPKs
    ret = runApkTool(["d", apkpath, "-o", apkdir])
  File "D:\.user\_app\patch-apk\patch-apk.py", line 160, in runApkTool
    proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=getStdout())
  File "C:\Users\Administrator\scoop\apps\python\current\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\scoop\apps\python\current\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by NickstaDB** [comment]
What app are you trying to rebuild?

**Comment by andrizmitnick** [comment]
Shopee - com.shopee.id

i also tried with facebook and line, same issue doesn't work. any clue what's wrong?
thanks before

**Comment by NickstaDB** [comment]
Do you have `apktool.bat` on your system PATH? Can you open a fresh command prompt, type `apktool.bat`, and get the apktool usage output?

Are you using the latest code from GitHub, unmodified? I would have expected the full package name to be listed in the first line of your output above. Does `com.shopee.id` appear in the output when you run `adb shell pm list packages`? What is the output from `adb shell pm path com.shopee.id`?

**Comment by andrizmitnick** [comment]
ah i'm sorry, my mistake, i edited the command output, forgot to explain that.
this one with facebook
```
PS D:\.user\_app\patch-apk> python3 patch-apk.py com.facebook.katana
Getting APK path(s) for package: com.facebook.katana
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/base.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_arservicesoptional.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_caffe2.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_caffe2pytorchsharedmodule.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_cgnativeplayer.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_codegenerator.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_livertcdeps.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_pages.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_rtc.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_rtc20.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_rtcdeps.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_shared2.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_shared4.apk
[+] APK path: /data/app/~~Zhkg_Iva9gwWN4CwysD6NA==/com.facebook.katana-idCRMic0OJvX8YFRKaCSfQ==/split_slam.apk

Pulling APK file(s) from device.
[+] Pulling: com.facebook.katana-base.apk
[+] Pulling: com.facebook.katana-split_arservicesoptional.apk
[+] Pulling: com.facebook.katana-split_caffe2.apk
[+] Pulling: com.facebook.katana-split_caffe2pytorchsharedmodule.apk
[+] Pulling: com.facebook.katana-split_cgnativeplayer.apk
[+] Pulling: com.facebook.katana-split_codegenerator.apk
[+] Pulling: com.facebook.katana-split_livertcdeps.apk
[+] Pulling: com.facebook.katana-split_pages.apk
[+] Pulling: com.facebook.katana-split_rtc.apk
[+] Pulling: com.facebook.katana-split_rtc20.apk
[+] Pulling: com.facebook.katana-split_rtcdeps.apk
[+] Pulling: com.facebook.katana-split_shared2.apk
[+] Pulling: com.facebook.katana-split_shared4.apk
[+] Pulling: com.facebook.katana-split_slam.apk

App bundle/split APK detected, rebuilding as a single APK.

Extracting individual APKs with apktool.
[+] Extracting: C:\Users\ADMINI~1\AppData\Local\Temp\tmp32s9_cfs\com.facebook.katana-base.apk
Traceback (most recent call last):
  File "D:\.user\_app\patch-apk\patch-apk.py", line 632, in <module>
    main()
  File "D:\.user\_app\patch-apk\patch-apk.py", line 30, in main
    apkfile = getTargetAPK(pkgname, apkpaths, tmppath, args.disable_styles_hack)
  File "D:\.user\_app\patch-apk\patch-apk.py", line 250, in getTargetAPK
    return combineSplitAPKs(pkgname, localapks, tmppath, disableStylesHack)
  File "D:\.user\_app\patch-apk\patch-apk.py", line 267, in combineSplitAPKs
    ret = runApkTool(["d", apkpath, "-o", apkdir])
  File "D:\.user\_app\patch-apk\patch-apk.py", line 160, in runApkTool
    proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=getStdout())
  File "C:\Users\Administrator\scoop\apps\python\current\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\scoop\apps\python\current\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by NickstaDB** [comment]
Can you run **`apktool.bat`** from a fresh command prompt?

**Comment by andrizmitnick** [comment]
everything's work now, the problem was the apktool i had. i use scoop to install apktool, had to uninstall and use the one from the official website. thank you!!

**Comment by NickstaDB** [comment]
No problem, glad you managed to get it working :)
