### ISSUE TITLE
Cant patch apk on windows

### ISSUE THREAD

**Issue by sanktanglia** [NickstaDB/patch-apk#38]
Rebuilding as a single APK.
Traceback (most recent call last):
  File "C:\Users\nesin\Downloads\patch-apk-master\patch-apk-master\patch-apk.py", line 653, in <module>
    main()
  File "C:\Users\nesin\Downloads\patch-apk-master\patch-apk-master\patch-apk.py", line 30, in main
    apkfile = getTargetAPK(pkgname, apkpaths, tmppath, args.disable_styles_hack)
  File "C:\Users\nesin\Downloads\patch-apk-master\patch-apk-master\patch-apk.py", line 265, in getTargetAPK
    return combineSplitAPKs(pkgname, localapks, tmppath, disableStylesHack)
  File "C:\Users\nesin\Downloads\patch-apk-master\patch-apk-master\patch-apk.py", line 317, in combineSplitAPKs
    elif getApktoolVersion() > pkg_resources.parse_version("2.4.2"):
  File "C:\Users\nesin\Downloads\patch-apk-master\patch-apk-master\patch-apk.py", line 157, in getApktoolVersion
    proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
NameError: name 'args' is not defined

**Comment by secure-77** [comment]
+1 have the same error with some app, also tried with parameter `--disable-styles-hack`

**Comment by maRci002** [comment]
https://github.com/NickstaDB/patch-apk/blob/24c64576afaedca7b10846d132a7d1ecd5b632b1/patch-apk.py#L317

I changed this line to `elif 1 == 1:`
