### ISSUE TITLE
failed on tik tok (com.zhiliaoapp.musically)

### ISSUE THREAD

**Issue by salisbury-espinosa** [NickstaDB/patch-apk#4]
**python ./patch-apk.py com.zhiliaoapp.musically**

Log:

```shell
Found public.xml in the base APK, fixing resource identifiers across split APKs.
[+] Resolving 229 resource identifiers.
[+] Located 229 true resource names.
[+] Updated 229 dummy resource names with true names in the base APK.
Traceback (most recent call last):
  File "./patch-apk.py", line 558, in <module>
    main()
  File "./patch-apk.py", line 29, in main
    apkfile = getTargetAPK(pkgname, apkpaths, tmppath, args.disable_styles_hack)
  File "./patch-apk.py", line 206, in getTargetAPK
    return combineSplitAPKs(pkgname, localapks, tmppath, disableStylesHack)
  File "./patch-apk.py", line 237, in combineSplitAPKs
    fixPublicResourceIDs(baseapkdir, splitapkpaths)
  File "./patch-apk.py", line 380, in fixPublicResourceIDs
    tree = xml.etree.ElementTree.parse(os.path.join(root, f))
  File "/home/user/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/home/user/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```
failed file: com.zhiliaoapp.musically-base/res/raw/keep.xml

Env 
os: Ubuntu 19.10 
apktool: 2.4.1
python: 3.7
version of apk: 15.5.44

if ignore it (try+except) -> error :

```shell
Rebuilding as a single APK.
[+] Building APK with apktool.
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/a/a/a/f;->values()[Landroid/a/a/a/f;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:825)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:268)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
	at brut.androlib.Androlib.buildSources(Androlib.java:350)
	at brut.androlib.Androlib.build(Androlib.java:302)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1098)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:821)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65922
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:348)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1058)
	... 11 more

Error: Failed to run 'apktool b /tmp/tmpaadlhhov/com.zhiliaoapp.musically-base'
```

**Comment by NickstaDB** [comment]
Thanks for the report @salisbury-espinosa. Some research and testing implies this might be related to obfuscation of the TikTok app. If you've managed to manually patch and rebuild the APK in question I'd be interested in finding out how and I'll consider implementing your solution in `patch-apk`. Otherwise, reversing an obfuscation tool (and getting into an ongoing battle with it) is definitely outside of the remit of this script!

**Comment by NickstaDB** [comment]
I should mention I did make some minor code changes off the back of this report, but nothing which results in successful patching of the TikTok app:

- The XML parsing exception is caught and processing is skipped.
- The script now tries to detect ProGuard/AndResGuard and warns that decompiling/recompiling may fail

**Comment by salisbury-espinosa** [comment]
> Otherwise, reversing an obfuscation tool (and getting into an ongoing battle with it) is definitely outside of the remit of this script!

yep:
https://github.com/iBotPeaches/Apktool/issues/2248#issuecomment-562545039
