### ISSUE TITLE
[Bug] INSTALL_FAILED_TEST_ONLY

### ISSUE THREAD

**Issue by Drjacky** [NickstaDB/patch-apk#43]
```bash
Installing the patched APK to the device.
adb: failed to install /var/folders/4c/13yp/T/tmp047fau5m/base.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
Error: Failed to run 'adb install /var/folders/4c/13yp/T/tmp047fau5m/base.apk'.
Run with --debug-output for more information.
```

**Comment by Drjacky** [comment]
So, I had to use `-t -r -d` as parameter for the installation but, then I got this:
```bash
Installing the patched APK to the device.
adb: failed to install /var/folders/4c/13yp5nx15q1_vfhb_cswvjt00000gn/T/tmpimgexqh1/base.apk:
Exception occurred while executing:
java.lang.IllegalArgumentException: No argument expected after "-t -r -d"
	at android.os.ShellCommand.getNextOption(ShellCommand.java:261)
	at com.android.server.pm.PackageManagerShellCommand.makeInstallParams(PackageManagerShellCommand.java:2139)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:903)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21862)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2865)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3963)
	at android.os.Binder.execTransact(Binder.java:731)
Error: Failed to run 'adb install /var/folders/4c/13yp5nx15q1_vfhb_cswvjt00000gn/T/tmpimgexqh1/base.apk'.
Run with --debug-output for more information.
➜  patch-apk git:(master) ✗
```
